### PR TITLE
Add ghrc container

### LINKED ISSUE #578: Publish the Docker image to GitHub container registry
Continue from #577.

### Related

- https://github.com/marp-team/marp-cli/issues/512

### PR DESCRIPTION
**Pull request by ankudinov**
Start building marp-cli container on GHRC.  
Fixes #578

### CODE REVIEW

**Comment by ankudinov** [comment]
The workflow is currently hardcoded to build on my branch to test before merging.  
Do not move out of draft status before changing that.

**Comment by ankudinov** [comment]
@yhatt I'd appreciate some help explaining the current Dockerfile logic. Unfortunately I have 0 skills in Node and it can be something trivial.  
However my build is using existing Dockerfile and fails with the following error:

```
#10 25.06 Error: Cannot find module './lib/marp-cli.js'
```

This probably comes from `marp-cli.js`: https://github.com/marp-team/marp-cli/blob/37cd0084ba9bed7a7fa1714e48a59ee4986c56cc/marp-cli.js#L5

I can not get how this file supposed to be created. The Dockerfile `COPY --chown=marp:marp . .` definitely not helping.

**Comment by ankudinov** [comment]
Here is the latest build log for the reference: https://github.com/ankudinov/marp-cli/actions/runs/9383539973/job/25837379955

**Comment by yhatt** [comment]
Marp team is currently using [CircleCI](https://github.com/marp-team/marp-cli/blob/main/.circleci/config.yml) to push the image to Docker Hub. The triggers and build steps are following:

- When updated `main` branch:
  1. CI will run the test for every supported Node.js versions. [→](https://github.com/marp-team/marp-cli/blob/37cd0084ba9bed7a7fa1714e48a59ee4986c56cc/.circleci/config.yml#L244-L252)
  2. If all tests passed, CI will build Marp CLI with the build command `yarn build`. At this time, necessary files will be generated in the `lib` directory. [→](https://github.com/marp-team/marp-cli/blob/37cd0084ba9bed7a7fa1714e48a59ee4986c56cc/.circleci/config.yml#L120-L128)
      - CI will store the `lib` directory as artifacts. (It calls "workspaces" in CircleCI)
      - Currently we are not building Marp CLI within Dockerfile, for making faster the build process for multi-arch images: https://github.com/marp-team/marp-cli/pull/402
  3. After building, CI will restore previously stored artifacts, build the multi-arch image `linux/amd64` and `linux/arm64` (for Apple Silicon), and publish it to the Docker Hub with `latest` tag. [→](https://github.com/marp-team/marp-cli/blob/37cd0084ba9bed7a7fa1714e48a59ee4986c56cc/.circleci/config.yml#L173-L180)

* When pushed the tag starting with `v.`:
  1. CI will build Marp CLI and generate the `lib` directory.
  2. After building, CI will build and publish the image tagged with the version number.

**Comment by yhatt** [comment]
#608 has been introduced building the multi-arch container image on GitHub Actions and pushing it into cross repositories, Docker Hub and GitHub Container Registry.

**Pull request closed without merging**
