### PR TITLE
Add presenter view to Bespoke template

### LINKED ISSUE #142: Presenter view for HTML
Will there ever be an option to have a presenter view in the HTML slide show, or to have a “pen” to draw on the slides?

Sorry if this is in the wrong project again—let me know if there’s a better place.

### PR DESCRIPTION
**Pull request by yhatt**
Add presenter view to Bespoke template by created Bespoke.js presenter plugin. Resolves #142.

presenter-view

Now we have the long-awaited feature! Presenter view for Marp presentation had strongly wanted in yhatt/marp#13 and yhatt/marp#30 from a lot of users.

It works with just a single HTML file in both of local and server. Thus, this feature does not break simplicity as a file converter.

### CODE REVIEW

**Comment by miguel-negrao** [comment]
I can report this branch works great on Linux Debian 10 with firefox 69.0 ! Really nice feature !

**Comment by asm0dey** [comment]
If this works fine — is there any chance that it will be merged in nearest future?

**Comment by asm0dey** [comment]
BTW works for like a charm after merging master into bespoke-presenter.

**Comment by yhatt** [comment]
This PR is still draft because of these:

- Timer is not yet work.
- We must fill tests for aiming to all green.

However, I've hesitated working because current plugin-based presenter view is feeling complex and lacked maintainability ([As mentioned in our blog](https://marp.app/blog/the-story-of-marp-next), Marp Next should keep simple coding for better maintainability).

Even so, I also could not think about better alternative proposal with supporting full features of HTML-based presentation provided by Marp / Marpit (Fragmented list, animations by CSS/GIF, interactivities by JS etc...). I'll work for this if contributors think this implementation was not so bad.

**Comment by asm0dey** [comment]
Well, I don't think that there really is choice :) 
Presentations for even 30-minute talks are almost impossible without presenter view. Theoretically export to PPTX could solve this problem, but it doesn't support features of presentation:

1. Animated content (GIFs, videos and so on)
2. Step-by-step slides (when bullet points appear one by one in presentation)

But possibly there is another way to support presenter view — like in revealjs. IIRC there is separate window with 2 iframes — current slide and next slide, rendered in these iframes. TBH I don't know how this window communicates with second one, but I'm prettysure it should be possible to understand from source.

**Comment by asm0dey** [comment]
Yes, here it is: https://github.com/hakimel/reveal.js/blob/master/plugin/notes/notes.js

Looks not too complex, but I'm not sure how it works with marp's plugins system.

**Comment by yhatt** [comment]
In fact reveal.js gives some hints to this implementation (e.g. embed next slide).

Our concerns has in view template rather than the logic of preseter view. We are using traditional `appendChild` chain but we think there is better way for maintainable partial templating. (e.g. pug, JSX)
https://github.com/marp-team/marp-cli/pull/157/files#diff-f1bccafb51f53567b36abeecb03980abR6-R19

**Comment by asm0dey** [comment]
Well, as engineer I fully understand you. On the other hand as end user I would prefer speaker view without timer and with not best-possible architecture to nonexistent speaker view.

Also as engineer I understand that after initial release it is possible to create ticket of improvement of existing solution (actually several independent improvements: add timer, add support for templates and so on).

Of course I adore pug (don't like JSX that much), but I believe it should be absolutely possible to migrate from vanilla JS to pug if it won't be maintainable enough.

Thank you for your work and extended answer!

**Comment by yhatt** [comment]
Honestly, core developer in the whole of Marp ecosystem is only me at the moment and I want to provide the robust tool for users. Please forgive me too obsessed with engineering!

Well, we could perform triage based on eager feedback like you. We would consider to work for merge without timer by filling tests.

**Comment by asm0dey** [comment]
Thank you for your great job again!

You're doing awesome job and I believe that you'll make a best decision possible!

**Comment by asm0dey** [comment]
BTW is there any way I can help you to fix tests? Right now they are failing because of not enough coverage. Possible I should help you to write tests to improve coverage?

**Comment by asm0dey** [comment]
Thank you so much!

**Pull request merged**
